### ISSUE TITLE
Question regarding you configuration

### ISSUE THREAD

**Issue by ceesvanegmond** [sinclairpaul/homeassistantconfig#2]
Hi there,
I've a question about your configuration. In a previous commit, you removed your MQTT sensors.
I noticed you use an entity `sensor.guest_room_temperature` in your configuration, but where do you define this entity? No YAML but only in the UI?

I'm wondering because I'm very interested in this setup (folders/files) e.d.

**Comment by sinclairpaul** [comment]
Hi, 

I'm sorry I never saw this for some reason, in case you were still wondering they are either via Zigbee (was Deconz, but switched to ZHA now, so they won't show in the config), or via ESPHome.
